'use strict';
const dropEditor={kind:'all',rows:[],row:null,config:null,base:null,revision:0,dirty:false};
const exchangeEditor={shops:[],shop:null,currencies:[],selected:new Set(),page:0,revision:0,nextShop:0,nextLineup:0,dirty:false};
const contentPicker={selected:new Map(),rows:[],page:0,serial:0,apply:null,labels:new Map()};
const contentKey=r=>`${r.type??r.reward_type}:${r.reward_typeid??r.reward_type_id}`;
const contentLabel=r=>contentPicker.labels.get(contentKey(r))||`${r.type}:${r.reward_typeid}`;
const contentReward=c=>({type:c.reward_type,reward_typeid:c.reward_type_id,num:1,card_lv:c.reward_type===6?1:0,card_fame:c.reward_type===6?1:0,card_love:0,card_skill_lv:c.reward_type===6?[1]:[]});
const targetLabel=t=>`第${t.battle_index+1}波 · 槽${t.enemy_index+1} ${t.name}`;
function contentDirty(name){return name==='drops'?dropEditor.dirty:name==='exchanges'?exchangeEditor.dirty:false}
function changedContent(name){const edit=name==='drops'?dropEditor:exchangeEditor;edit.dirty=true;$(name==='drops'?'#drop-summary':'#exchange-summary').textContent='有未保存的修改'}
async function contentAction(name,fn){if(policyBusy(name))return;state.publishing.add(name);updatePolicyControls();try{await fn()}catch(e){toast(e.message,true)}finally{state.publishing.delete(name);updatePolicyControls()}}
async function resolveContentLabels(rewards){
  const keys=[...new Map(rewards.map(r=>[contentKey(r),{reward_type:r.type,reward_type_id:r.reward_typeid,quantity:1}])).values()];
  for(let i=0;i<keys.length;i+=100){const data=await api('/api/catalog/resolve',{method:'POST',body:JSON.stringify({rewards:keys.slice(i,i+100)})});for(const c of data.entries||[])contentPicker.labels.set(contentKey(c),c.name)}
}
function downloadContent(value,name){const url=URL.createObjectURL(new Blob([JSON.stringify(value,null,2)],{type:'application/json'}));const link=document.createElement('a');link.href=url;link.download=name;link.click();setTimeout(()=>URL.revokeObjectURL(url),1000)}
async function importContent(input){try{const file=input.files[0];if(!file)return null;if(file.size>1024*1024)throw new Error('方案文件超过1MiB');return JSON.parse(await file.text())}finally{input.value=''}}

async function loadDropEditor(){const data=await api('/api/boss-drops');dropEditor.rows=data.bosses;filterDropSelect();await selectDrop(Number($('#drop-select').value)||dropEditor.row?.boss_id)}
function filterDropSelect(){
  const q=$('#drop-search').value.trim().toLowerCase(),id=dropEditor.row?.boss_id;
  const rows=dropEditor.rows.filter(b=>(dropEditor.kind==='all'||b.category===dropEditor.kind)&&(!q||`${b.name} ${b.difficulty} ${b.boss_id}`.toLowerCase().includes(q)));
  $$('#drop-kinds button').forEach(b=>b.classList.toggle('active',b.dataset.kind===dropEditor.kind));
  const preserve=!!dropEditor.row;
  $('#drop-select').innerHTML=(preserve||!rows.length?`<option value="">${rows.length?'请选择难度（当前草稿保留）':'没有匹配的难度'}</option>`:'')+rows.map(b=>`<option value="${b.boss_id}">${esc(b.name)} · ${esc(b.difficulty)} · ${b.boss_id}</option>`).join('');
  if(rows.some(b=>b.boss_id===id))$('#drop-select').value=id;
}
$$('#drop-kinds button').forEach(b=>b.onclick=()=>{dropEditor.kind=b.dataset.kind;filterDropSelect()});
async function selectDrop(id){
  if(!id)return;const data=await api(`/api/boss-drops?boss_id=${id}`);
  dropEditor.row=data.boss;dropEditor.base=data.base;dropEditor.config=structuredClone(data.config);dropEditor.config.enemy_drops??=[];dropEditor.revision=data.revision;dropEditor.dirty=false;
  await resolveContentLabels([...dropEditor.config.enemy_drops.map(d=>d.reward),...(dropEditor.config.fame_rewards||[])]);
  $('#drop-target').innerHTML=data.boss.targets.map((t,i)=>`<option value="${i}">${esc(targetLabel(t))}</option>`).join('');
  const siblings=dropEditor.rows.filter(b=>b.group_id===data.boss.group_id&&b.boss_id!==id);
  $('#drop-copy-from').innerHTML=siblings.map(b=>`<option value="${b.boss_id}">${esc(b.difficulty)} · ${b.boss_id}</option>`).join('');
  $('#drop-copy-targets').innerHTML=siblings.map(b=>`<label><input type="checkbox" value="${b.boss_id}"> ${esc(b.difficulty)}</label>`).join('');
  $('#drop-current').textContent=`正在编辑：${data.boss.name} · ${data.boss.difficulty} · ${id}`;$('#drop-version').textContent=`配置 v${data.revision}`;$('#drop-summary').textContent='选择怪物或部位后可批量添加奖励';renderDropRows();
}
function renderDropRows(){
  renderFameRows();
  const targets=dropEditor.row?.targets||[],drops=dropEditor.config?.enemy_drops||[];
  $('#drop-add').disabled=!targets.length;$('#drop-save').disabled=!targets.length;
  $('#drop-rows').innerHTML=drops.map((d,i)=>`<tr data-drop="${i}"><td><select data-field="target" aria-label="掉落目标">${targets.map((t,j)=>`<option value="${j}" ${d.battle_index===t.battle_index&&d.enemy_index===t.enemy_index?'selected':''}>${esc(targetLabel(t))}</option>`).join('')}</select></td><td>${esc(contentLabel(d.reward))}<span class="sub">${d.reward.reward_typeid}</span></td><td><input data-field="num" type="number" min="1" max="${d.reward.type===6?100:10000000}" value="${d.reward.num}" aria-label="奖励数量"></td><td><input data-field="chance" type="number" min="0" max="100" step="0.0001" value="${(d.chance_per_million??1000000)/10000}" aria-label="掉落概率"></td><td><button class="secondary" data-remove="${i}">移除</button></td></tr>`).join('')||'<tr><td colspan="5" class="empty">暂无掉落。点击“添加奖励”选择卡牌、素材或道具。</td></tr>';
  $$('#drop-rows [data-field]').forEach(el=>el.onchange=()=>{const d=drops[Number(el.closest('tr').dataset.drop)];if(el.dataset.field==='target'){const t=targets[Number(el.value)];d.battle_index=t.battle_index;d.enemy_index=t.enemy_index}else if(el.dataset.field==='num')d.reward.num=Number(el.value);else d.chance_per_million=Math.round(Number(el.value)*10000);changedContent('drops')});
  $$('#drop-rows [data-remove]').forEach(b=>b.onclick=()=>{drops.splice(Number(b.dataset.remove),1);changedContent('drops');renderDropRows()});
}
$('#drop-search').oninput=filterDropSelect;
$('#drop-select').onchange=()=>{const id=Number($('#drop-select').value);if(!id)return;if(dropEditor.dirty&&!confirm('切换难度会放弃未保存的修改，继续？')){$('#drop-select').value=dropEditor.row.boss_id;return}return contentAction('drops',()=>selectDrop(id))};
$('#drop-add').onclick=()=>openContentPicker(rows=>{const target=dropEditor.row.targets[Number($('#drop-target').value)];if(!target)throw new Error('请选择掉落目标');if(dropEditor.config.enemy_drops.length+rows.length>120)throw new Error('每个难度最多120项');for(const row of rows)dropEditor.config.enemy_drops.push({battle_index:target.battle_index,enemy_index:target.enemy_index,reward:contentReward(row),chance_per_million:1000000});changedContent('drops');renderDropRows()});
$('#drop-set-chance').onclick=()=>{const chance=Number($('#drop-chance-all').value);if(!Number.isFinite(chance)||chance<0||chance>100)return toast('概率须为0至100',true);for(const d of dropEditor.config.enemy_drops)d.chance_per_million=Math.round(chance*10000);changedContent('drops');renderDropRows()};
$('#drop-base').onclick=()=>{if(!dropEditor.base)return;if(!confirm('载入包内默认掉落？保存前可继续编辑。'))return;dropEditor.config=structuredClone(dropEditor.base);dropEditor.config.enemy_drops??=[];changedContent('drops');renderDropRows()};
$('#drop-copy').onclick=()=>contentAction('drops',async()=>{const id=Number($('#drop-copy-from').value);if(!id)return;const data=await api(`/api/boss-drops?boss_id=${id}`);const rows=data.config.enemy_drops||[];if(!dropTargetsMatch(rows,dropEditor.row))throw new Error('此难度的波次或部位不同，不能直接复制');await resolveContentLabels(rows.map(d=>d.reward));dropEditor.config.enemy_drops=structuredClone(rows);dropEditor.config.fame_rewards=structuredClone(data.config.fame_rewards??null);await resolveContentLabels(dropEditor.config.fame_rewards||[]);changedContent('drops');renderDropRows()});
function dropTargetsMatch(rows,boss){return rows.every(d=>boss.targets.some(t=>t.battle_index===d.battle_index&&t.enemy_index===d.enemy_index))}
$('#drop-export').onclick=()=>downloadContent(dropEditor.config,`boss-drops-${dropEditor.row.boss_id}.json`);
$('#drop-import').onchange=()=>contentAction('drops',async()=>{const config=await importContent($('#drop-import'));if(!config)return;if(!Array.isArray(config.enemy_drops)||config.enemy_drops.length>120||!dropTargetsMatch(config.enemy_drops,dropEditor.row))throw new Error('掉落数组或波次／部位不匹配');await resolveContentLabels(config.enemy_drops.map(d=>d.reward));if(config.fame_rewards!=null&&!Array.isArray(config.fame_rewards))throw new Error("名声奖励须为数组");await resolveContentLabels(config.fame_rewards||[]);dropEditor.config={boss_id:dropEditor.row.boss_id,enemy_drops:config.enemy_drops,fame_rewards:config.fame_rewards??null};changedContent('drops');renderDropRows()});
$('#drop-save').onclick=()=>contentAction('drops',async()=>{if(!dropEditor.config)return;const ids=[dropEditor.row.boss_id,...$$('#drop-copy-targets input:checked').map(el=>Number(el.value))];for(const id of ids){const boss=dropEditor.rows.find(b=>b.boss_id===id);if(!dropTargetsMatch(dropEditor.config.enemy_drops,boss))throw new Error(`${boss.difficulty}的波次或部位不同，请单独配置`)}if(!confirm(`保存 ${ids.length} 个难度、每个 ${dropEditor.config.enemy_drops.length} 项掉落？\n配置仅用于后续开战。`))return;const data=await api('/api/boss-drops',{method:'PUT',body:JSON.stringify({expected_revision:dropEditor.revision,configs:ids.map(id=>({...dropEditor.config,boss_id:id}))})});dropEditor.revision=data.revision;dropEditor.dirty=false;$('#drop-version').textContent=`配置 v${data.revision}`;$('#drop-summary').textContent='已保存；掉落展示和结算使用同一配置';state.loaded.delete('audit');toast('掉落配置已保存')});

async function loadExchangeEditor(){
  const data=await api('/api/exchanges');exchangeEditor.shops=data.shops;exchangeEditor.revision=data.revision;exchangeEditor.nextShop=data.next_shop_id;exchangeEditor.nextLineup=data.next_lineup_id;exchangeEditor.templates=data.templates;
  if(!exchangeEditor.currencies.length){let rows=[];for(let offset=0;;){const page=await api(`/api/catalog?kind=item&limit=200&offset=${offset}`);rows.push(...page.entries);offset+=page.entries.length;if(offset>=page.total)break;if(!page.entries.length)throw new Error('货币目录加载中断')}exchangeEditor.currencies=rows;for(const c of rows)contentPicker.labels.set(contentKey(c),c.name)}
  $('#exchange-currency').innerHTML=currencyOptions(4000);
  const id=exchangeEditor.shop?.trade_shopid;renderExchangeSelect();await selectExchange(exchangeEditor.shops.some(s=>s.trade_shopid===id)?id:exchangeEditor.shops[0]?.trade_shopid);
}
function currencyOptions(id){return exchangeEditor.currencies.map(c=>`<option value="${c.reward_type_id}" ${id===c.reward_type_id?'selected':''}>${esc(c.name)} · ${c.reward_type_id}</option>`).join('')}
function renderExchangeSelect(){$('#exchange-select').innerHTML=exchangeEditor.shops.map(s=>`<option value="${s.trade_shopid}">${esc(s.name)}${s.disabled?'（关闭）':''}</option>`).join('')}
async function selectExchange(id){const shop=exchangeEditor.shops.find(s=>s.trade_shopid===id);if(!shop)return;exchangeEditor.shop=structuredClone(shop);exchangeEditor.selected.clear();exchangeEditor.page=0;exchangeEditor.dirty=false;$('#exchange-select').value=id;await resolveContentLabels(shop.lineups.flatMap(l=>l.rewards));renderExchangeForm()}
function renderExchangeForm(){const s=exchangeEditor.shop;$('#exchange-name').value=s.name;$('#exchange-text').value=s.text;$('#exchange-enabled').checked=!s.disabled;$('#exchange-tab').value=s.tab_type;$('#exchange-end').value=s.end_time&&s.end_time<2147483647?localTimeInput(s.end_time):'';$('#exchange-version').textContent=`配置 v${exchangeEditor.revision}`;$('#exchange-summary').textContent='按商品 ID 保留每位玩家的累计兑换次数';renderExchangeRows()}
function filteredOffers(){const q=$('#exchange-search').value.trim().toLowerCase();return (exchangeEditor.shop?.lineups||[]).filter(l=>!q||`${l.lineup_name} ${l.lineupid} ${l.rewards[0].reward_typeid}`.toLowerCase().includes(q))}
function renderExchangeRows(){
  const rows=filteredOffers();exchangeEditor.page=renderPager('exchange',exchangeEditor.page,rows.length,30,page=>{exchangeEditor.page=page;renderExchangeRows()});
  $('#exchange-selection').textContent=`已选 ${exchangeEditor.selected.size} / 全店 ${exchangeEditor.shop.lineups.length} 项`;
  $('#exchange-rows').innerHTML=rows.slice(exchangeEditor.page*30,(exchangeEditor.page+1)*30).map(l=>`<tr data-offer="${l.lineupid}"><td><input data-field="select" type="checkbox" aria-label="选择商品" ${exchangeEditor.selected.has(l.lineupid)?'checked':''}></td><td><input data-field="enabled" type="checkbox" aria-label="上架" ${l.disabled?'':'checked'}></td><td><input class="offer-name" data-field="name" maxlength="60" value="${esc(l.lineup_name)}" aria-label="商品名称"><span class="sub">${esc(contentLabel(l.rewards[0]))} · ${l.rewards[0].reward_typeid}<br>商品 ${l.lineupid}</span></td><td><input data-field="num" type="number" min="1" max="${[14,16,18].includes(l.rewards[0].type)?1:[6,15,19].includes(l.rewards[0].type)?100:10000000}" value="${l.rewards[0].num}" aria-label="商品数量"></td><td><select data-field="currency" aria-label="兑换货币">${currencyOptions(l.prices[0].id)}</select></td><td><input data-field="price" type="number" min="1" max="10000000" value="${l.prices[0].num}" aria-label="单价"></td><td><input data-field="stock" type="number" min="-1" max="999999" value="${l.stock_num}" aria-label="每人限购"></td></tr>`).join('')||'<tr><td colspan="7" class="empty">暂无匹配商品。可从目录批量添加。</td></tr>';
  $$('#exchange-rows [data-field]').forEach(el=>el.onchange=()=>{const id=Number(el.closest('tr').dataset.offer),l=exchangeEditor.shop.lineups.find(l=>l.lineupid===id);switch(el.dataset.field){case 'select':el.checked?exchangeEditor.selected.add(id):exchangeEditor.selected.delete(id);$('#exchange-selection').textContent=`已选 ${exchangeEditor.selected.size} 项`;return;case 'enabled':l.disabled=!el.checked;break;case 'name':l.lineup_name=el.value.trim();break;case 'num':l.rewards[0].num=Number(el.value);break;case 'currency':l.prices[0].id=Number(el.value);break;case 'price':l.prices[0].num=Number(el.value);break;case 'stock':l.stock_num=Number(el.value);break}changedContent('exchanges')});
}
function exchangeForm(){const s=exchangeEditor.shop;s.name=$('#exchange-name').value.trim();s.text=$('#exchange-text').value.trim();s.disabled=!$('#exchange-enabled').checked;s.tab_type=Number($('#exchange-tab').value);s.end_time=unixInput('#exchange-end')||2147483647;return s}
['#exchange-name','#exchange-text','#exchange-enabled','#exchange-tab','#exchange-end'].forEach(id=>$(id).onchange=()=>{exchangeForm();changedContent('exchanges')});
$('#exchange-select').onchange=()=>{const id=Number($('#exchange-select').value);if(exchangeEditor.dirty&&!confirm('切换会放弃未保存的修改，继续？')){$('#exchange-select').value=exchangeEditor.shop.trade_shopid;return}return contentAction('exchanges',()=>selectExchange(id))};
function newExchange(copy){if(exchangeEditor.dirty&&!confirm('新建会放弃当前未保存的修改，继续？'))return;const shop=copy?structuredClone(exchangeForm()):{name:'新兑换所',text:'常驻兑换，库存按账号累计。',shop_type:1,tab_type:1,end_time:2147483647,is_new:0,pictid:0,lineups:[],evidence:'LOCAL_POLICY_ADMIN'};shop.trade_shopid=exchangeEditor.nextShop++;shop.disabled=true;if(copy){shop.name=`${shop.name}副本`.slice(0,40);for(const l of shop.lineups)l.lineupid=exchangeEditor.nextLineup++}exchangeEditor.shops.push(shop);renderExchangeSelect();exchangeEditor.shop=structuredClone(shop);exchangeEditor.selected.clear();exchangeEditor.page=0;$('#exchange-select').value=shop.trade_shopid;renderExchangeForm();changedContent('exchanges')}
$('#exchange-new').onclick=()=>newExchange(false);$('#exchange-clone').onclick=()=>newExchange(true);
function exchangeDefaults(){const price=Number($('#exchange-price').value),stock=Number($('#exchange-stock').value),currency=Number($('#exchange-currency').value);if(!Number.isInteger(price)||price<1||price>10000000||!Number.isInteger(stock)||stock===0||stock< -1||stock>999999||!currency)throw new Error('请检查货币、单价和限兑数量（-1表示不限量）');return {price,stock,currency}}
function addExchangeOffers(rows){const d=exchangeDefaults(),s=exchangeEditor.shop;if(s.lineups.length+rows.length>500)throw new Error('每个兑换所最多500项');for(const row of rows){const reward=contentReward(row);if(s.lineups.some(l=>contentKey(l.rewards[0])===contentKey(reward)&&!l.disabled))continue;const id=exchangeEditor.nextLineup++;s.lineups.push({lineupid:id,lineup_name:row.name,stock_num:d.stock,is_lineup_new:0,is_lineup_old:0,pictid:0,prices:[{type:4,id:d.currency,num:d.price,point_card_condition:[]}],rewards:[reward],evidence:'LOCAL_POLICY_ADMIN'});exchangeEditor.selected.add(id)}changedContent('exchanges');renderExchangeRows()}
$('#exchange-add').onclick=()=>openContentPicker(addExchangeOffers,['material','card','item','sphere','buddy','costume','stamp','honor']);
for(const kind of ['fusion','evolution'])$('#exchange-'+kind).onclick=()=>{try{const rows=exchangeEditor.templates[kind]||[];for(const c of rows)contentPicker.labels.set(contentKey(c),c.name);addExchangeOffers(rows)}catch(e){toast(e.message,true)}};
$('#exchange-search').oninput=()=>{exchangeEditor.page=0;renderExchangeRows()};
$('#exchange-select-page').onclick=()=>{filteredOffers().slice(exchangeEditor.page*30,(exchangeEditor.page+1)*30).forEach(l=>exchangeEditor.selected.add(l.lineupid));renderExchangeRows()};$('#exchange-clear').onclick=()=>{exchangeEditor.selected.clear();renderExchangeRows()};
$('#exchange-batch').onclick=()=>{try{const d=exchangeDefaults();for(const l of exchangeEditor.shop.lineups)if(exchangeEditor.selected.has(l.lineupid)){l.prices=[{type:4,id:d.currency,num:d.price,point_card_condition:[]}];l.stock_num=d.stock}changedContent('exchanges');renderExchangeRows()}catch(e){toast(e.message,true)}};
for(const [id,disabled] of [['#exchange-on',false],['#exchange-off',true]])$(id).onclick=()=>{for(const l of exchangeEditor.shop.lineups)if(exchangeEditor.selected.has(l.lineupid))l.disabled=disabled;changedContent('exchanges');renderExchangeRows()};
$('#exchange-export').onclick=()=>downloadContent(exchangeForm(),`exchange-${exchangeEditor.shop.trade_shopid}.json`);
$('#exchange-import').onchange=()=>contentAction('exchanges',async()=>{const shop=await importContent($('#exchange-import'));if(!shop)return;if(!Array.isArray(shop.lineups)||shop.lineups.length>500||shop.lineups.some(l=>!Array.isArray(l.rewards)||l.rewards.length!==1||!Array.isArray(l.prices)||l.prices.length!==1))throw new Error('商品格式无效');if(shop.trade_shopid!==exchangeEditor.shop.trade_shopid)throw new Error('方案与当前兑换所ID不同；如需复制请使用“复制为新兑换所”');await resolveContentLabels(shop.lineups.flatMap(l=>l.rewards));exchangeEditor.shop=shop;for(const l of shop.lineups)exchangeEditor.nextLineup=Math.max(exchangeEditor.nextLineup,l.lineupid+1);exchangeEditor.selected.clear();renderExchangeForm();changedContent('exchanges')});
$('#exchange-save').onclick=()=>contentAction('exchanges',async()=>{const shop=exchangeForm();if(!confirm(`保存「${shop.name}」？\n${shop.disabled?'兑换所关闭':`${shop.lineups.filter(l=>!l.disabled).length}项上架商品`}；已有兑换次数保留。`))return;const data=await api(`/api/exchanges/${shop.trade_shopid}`,{method:'PUT',body:JSON.stringify({expected_revision:exchangeEditor.revision,shop})});exchangeEditor.revision=data.revision;exchangeEditor.shop=data.shop;const i=exchangeEditor.shops.findIndex(s=>s.trade_shopid===shop.trade_shopid);exchangeEditor.shops[i]=structuredClone(data.shop);exchangeEditor.dirty=false;renderExchangeSelect();$('#exchange-select').value=shop.trade_shopid;$('#exchange-version').textContent=`配置 v${data.revision}`;$('#exchange-summary').textContent='已保存；玩家重新打开兑换所后可见';state.loaded.delete('audit');toast('兑换所已保存')});

function openContentPicker(apply,kinds=['material','card','item']){const names={currency:'货币',card:'卡牌',material:'素材卡',item:'道具',sphere:'召唤石',buddy:'传承卡',costume:'变身皮肤',stamp:'对话／表情',honor:'称号'};$('#content-kind').innerHTML=kinds.map(k=>`<option value="${k}">${names[k]}</option>`).join('');$('#content-search').value='';contentPicker.apply=apply;contentPicker.selected.clear();contentPicker.page=0;$('#content-picker').classList.add('open');loadContentCatalog()}
async function loadContentCatalog(){
  const serial=++contentPicker.serial;$('#content-apply').disabled=true;
  const isCard=$('#content-kind').value==='card';$('#content-job').hidden=!isCard;$('#content-source').hidden=!isCard;$('#content-rarity').hidden=!($('#content-kind').value==='card');
  try{const kind=$('#content-kind').value,p=new URLSearchParams({kind,q:$('#content-search').value.trim(),limit:'48',offset:String(contentPicker.page*48),arthur_type:kind==='card'?$('#content-job').value:'0',source:kind==='card'?$('#content-source').value:'',rarity:(kind==='card')?$('#content-rarity').value:'0'});const data=await api(`/api/catalog?${p}`);if(serial!==contentPicker.serial)return;contentPicker.rows=data.entries;for(const c of data.entries)contentPicker.labels.set(contentKey(c),c.name);contentPicker.page=renderPager('content',contentPicker.page,data.total,48,page=>{contentPicker.page=page;loadContentCatalog()});renderContentCatalog()}catch(e){toast(e.message,true)}finally{if(serial===contentPicker.serial)$('#content-apply').disabled=false}
}
function renderContentCatalog(){
  $('#content-selected').textContent=`已选${contentPicker.selected.size}项，跨页保留`;
  $('#content-catalog').innerHTML=contentPicker.rows.map(c=>`<button class="catalog-card ${contentPicker.selected.has(contentKey(c))?'selected':''}" data-key="${contentKey(c)}" ${c.resource_state==='unavailable'?'disabled':''}><div class="thumb">${image(c.image_url,c.name)}</div><div class="catalog-copy"><b>${esc(c.name)}</b><span class="sub">${c.reward_type_id} ${c.kind==='card'?cardJobName(c.arthur_type):''} ${cardStars(c)}</span><span class="sub">${esc(c.kind==='card'?cardSourceDescription(c):c.detail||'')}</span></div></button>`).join('');
  $$('#content-catalog [data-key]').forEach(b=>b.onclick=()=>{const c=contentPicker.rows.find(c=>contentKey(c)===b.dataset.key);contentPicker.selected.has(b.dataset.key)?contentPicker.selected.delete(b.dataset.key):contentPicker.selected.set(b.dataset.key,c);renderContentCatalog()});
}
['#content-kind','#content-job','#content-source','#content-rarity'].forEach(id=>$(id).onchange=()=>{contentPicker.page=0;loadContentCatalog()});let contentSearchTimer;$('#content-search').oninput=()=>{clearTimeout(contentSearchTimer);contentSearchTimer=setTimeout(()=>{contentPicker.page=0;loadContentCatalog()},200)};
$('#content-select-page').onclick=()=>{contentPicker.rows.filter(c=>c.resource_state!=='unavailable').forEach(c=>contentPicker.selected.set(contentKey(c),c));renderContentCatalog()};$('#content-clear').onclick=()=>{contentPicker.selected.clear();renderContentCatalog()};
$('#content-cancel').onclick=()=>{$('#content-picker').classList.remove('open');contentPicker.serial++};
$('#content-apply').onclick=()=>{try{contentPicker.apply([...contentPicker.selected.values()]);$('#content-picker').classList.remove('open')}catch(e){toast(e.message,true)}};

$('#exchange-unselect-page').onclick=()=>{filteredOffers().slice(exchangeEditor.page*30,(exchangeEditor.page+1)*30).forEach(l=>exchangeEditor.selected.delete(l.lineupid));renderExchangeRows()};
$('#content-unselect-page').onclick=()=>{contentPicker.rows.forEach(c=>contentPicker.selected.delete(contentKey(c)));renderContentCatalog()};

function renderFameRows(){
  const pool=dropEditor.config?.fame_rewards;
  $('#fame-mode').value=pool==null?'default':'custom';
  $('#fame-rows').innerHTML=pool==null?'<tr><td colspan="3" class="sub">从副本默认掉落选择名声奖励</td></tr>':pool.map((r,i)=>`<tr><td>${esc(contentLabel(r))}<span class="sub">${r.reward_typeid}</span></td><td><input data-fame-num="${i}" type="number" min="1" max="${r.type===6?100:10000000}" value="${r.num}" aria-label="名声奖励数量"></td><td><button class="secondary" data-fame-remove="${i}">移除</button></td></tr>`).join('')||'<tr><td colspan="3" class="sub">此难度名声奖励已关闭</td></tr>';
  $$('[data-fame-num]').forEach(el=>el.onchange=()=>{pool[Number(el.dataset.fameNum)].num=Number(el.value);changedContent('drops')});
  $$('[data-fame-remove]').forEach(el=>el.onclick=()=>{pool.splice(Number(el.dataset.fameRemove),1);changedContent('drops');renderFameRows()});
}
$('#fame-mode').onchange=()=>{if(!dropEditor.config)return;dropEditor.config.fame_rewards=$('#fame-mode').value==='default'?null:[];changedContent('drops');renderFameRows()};
$('#fame-add').onclick=()=>openContentPicker(rows=>{if(!dropEditor.config)throw new Error('请选择难度');const pool=dropEditor.config.fame_rewards??=[];if(pool.length+rows.length>120)throw new Error('名声候选最多120项');pool.push(...rows.map(contentReward));changedContent('drops');renderFameRows()});
$('#fame-clear').onclick=()=>{if(!dropEditor.config)return;dropEditor.config.fame_rewards=[];changedContent('drops');renderFameRows()};
