'use strict';
const collectionEditor={config:null,revision:0,dirty:false,honorID:0,boxID:0,icons:[],nextHonor:0,nextBox:0,nextFunction:0};
async function loadCollections(){
  const data=await api('/api/collections');
  collectionEditor.config=data.config;collectionEditor.revision=data.revision;collectionEditor.dirty=false;
  collectionEditor.nextHonor=data.next_honor_id;collectionEditor.nextBox=data.next_item_id;collectionEditor.nextFunction=data.next_function_value;collectionEditor.icons=data.icons;
  collectionEditor.honorID=data.config.honors.some(h=>h.honor_id===collectionEditor.honorID)?collectionEditor.honorID:data.config.honors[0]?.honor_id||0;
  collectionEditor.boxID=data.config.boxes.some(b=>b.item.item_id===collectionEditor.boxID)?collectionEditor.boxID:data.config.boxes[0]?.item.item_id||0;
  await resolveContentLabels(data.config.boxes.flatMap(b=>b.profile.reward_pool.map(x=>x.reward)).filter(r=>!data.config.honors.some(h=>r.type===18&&r.reward_typeid===h.honor_id)));
  renderCollections();$('#collection-status').textContent='配置保存为草稿；生成更新包、覆盖资源并重启后在游戏中生效。';
}
function currentHonor(){return collectionEditor.config?.honors.find(h=>h.honor_id===collectionEditor.honorID)}
function currentBox(){return collectionEditor.config?.boxes.find(b=>b.item.item_id===collectionEditor.boxID)}
function collectionChanged(){collectionEditor.dirty=true;$('#collection-status').textContent='有未保存的修改；保存后可生成资源更新包。';updateDraftIndicators()}
function renderCollections(){
  const e=collectionEditor;$('#collection-version').textContent=`配置 v${e.revision}`;
  $('#honor-select').innerHTML=e.config.honors.map(h=>`<option value="${h.honor_id}">${esc(h.name)} · ${h.honor_id}</option>`).join('')||'<option value="">暂无自定义称号</option>';
  $('#box-select').innerHTML=e.config.boxes.map(b=>`<option value="${b.item.item_id}">${esc(b.item.name)} · ${b.item.item_id}</option>`).join('')||'<option value="">暂无自定义礼盒</option>';
  $('#honor-select').value=e.honorID||'';$('#box-select').value=e.boxID||'';
  $('#box-custom-honor').innerHTML=e.config.honors.map(h=>`<option value="${h.honor_id}">${esc(h.name)} · ${h.honor_id}</option>`).join('')||'<option value="">先新增称号</option>';
  for(const h of e.config.honors)contentPicker.labels.set(`18:${h.honor_id}`,h.name);
  $('#box-icon').innerHTML=e.icons.map(i=>`<option value="${i.id}">${esc(i.name)} · 图标 ${i.pict_id}</option>`).join('');
  renderCollectionHonor();renderCollectionBox();updateDraftIndicators();
}
function renderCollectionHonor(){const h=currentHonor();$('#honor-fields').disabled=!h;$('#honor-id').value=h?.honor_id||'';$('#honor-name').value=h?.name||'';$$('#honor-slots input').forEach(el=>el.checked=!!(h?.slot_mask&Number(el.value)))}
function renderCollectionBox(){const b=currentBox();$('#box-fields').disabled=!b;$('#box-id').value=b?.item.item_id||'';$('#box-name').value=b?.item.name||'';$('#box-description').value=b?.item.description||'';$('#box-icon').value=b?.icon_source_id||'';$('#box-maximum').value=b?.item.max_owned||99999;$('#box-add-rewards').disabled=!b;$('#box-add-honor').disabled=!b||!collectionEditor.config.honors.length;renderBoxPool()}
function renderBoxPool(){
  const b=currentBox(),pool=b?.profile.reward_pool||[],total=pool.reduce((sum,x)=>sum+Number(x.weight||0),0);
  $('#box-pool-summary').textContent=b?`${b.item.name} · ${pool.length}项 · 总权重 ${total}`:'请选择礼盒';
  $('#box-reward-rows').innerHTML=pool.map((x,i)=>{const r=x.reward;return `<tr data-box-reward="${i}"><td>${esc(contentLabel(r))}<span class="sub">${r.type}:${r.reward_typeid}</span></td><td><input data-field="num" aria-label="奖励数量" type="number" min="1" max="${[14,18].includes(r.type)?1:r.type===6?100:10000000}" value="${r.num}" ${[14,18].includes(r.type)?'readonly':''}></td><td><input data-field="weight" aria-label="奖励权重" type="number" min="1" max="1000000000" value="${x.weight}"></td><td data-probability>${total>0?(100*x.weight/total).toFixed(3):'0'}%</td><td>${r.type===6?`<input data-field="level" aria-label="卡牌等级" type="number" min="1" value="${r.card_lv||1}">`:'—'}</td><td><button class="danger" data-remove>移除</button></td></tr>`}).join('')||'<tr><td colspan="6" class="empty">先选择礼盒，再添加奖励。</td></tr>';
  $$('#box-reward-rows [data-field]').forEach(input=>input.oninput=()=>{const index=Number(input.closest('tr').dataset.boxReward),x=pool[index],n=Number(input.value);if(input.dataset.field==='weight')x.weight=n;else if(input.dataset.field==='num')x.reward.num=n;else x.reward.card_lv=n;collectionChanged();const sum=pool.reduce((s,x)=>s+x.weight,0);$$('#box-reward-rows tr[data-box-reward]').forEach(row=>{const x=pool[Number(row.dataset.boxReward)];row.querySelector('[data-probability]').textContent=sum>0?`${(100*x.weight/sum).toFixed(3)}%`:'0%'});$('#box-pool-summary').textContent=`${b.item.name} · ${pool.length}项 · 总权重 ${sum}`});
  $$('#box-reward-rows [data-remove]').forEach(button=>button.onclick=()=>{pool.splice(Number(button.closest('tr').dataset.boxReward),1);collectionChanged();renderBoxPool()});
}
$('#honor-select').onchange=()=>{collectionEditor.honorID=Number($('#honor-select').value);renderCollectionHonor()};
$('#box-select').onchange=()=>{collectionEditor.boxID=Number($('#box-select').value);renderCollectionBox()};
$('#honor-name').oninput=()=>{const h=currentHonor();if(!h)return;h.name=$('#honor-name').value;contentPicker.labels.set(`18:${h.honor_id}`,h.name);$('#honor-select option:checked').textContent=`${h.name} · ${h.honor_id}`;const option=$$('#box-custom-honor option').find(o=>Number(o.value)===h.honor_id);if(option)option.textContent=`${h.name} · ${h.honor_id}`;collectionChanged();renderBoxPool()};
$$('#honor-slots input').forEach(el=>el.onchange=()=>{const h=currentHonor();if(h){h.slot_mask=$$('#honor-slots input:checked').reduce((mask,x)=>mask|Number(x.value),0);collectionChanged()}});
$('#honor-new').onclick=()=>{const h={honor_id:collectionEditor.nextHonor++,name:'新称号',slot_mask:8,same_card_id:0,get_type:0,default_owned:false};collectionEditor.config.honors.push(h);collectionEditor.honorID=h.honor_id;collectionChanged();renderCollections();$('#honor-name').focus();$('#honor-name').select()};
$('#box-new').onclick=()=>{const icon=collectionEditor.icons.find(i=>i.id===8887)||collectionEditor.icons[0];if(!icon){toast('没有可复用的礼盒图标',true);return}const id=collectionEditor.nextBox++,fn=collectionEditor.nextFunction++;collectionEditor.config.boxes.push({item:{item_id:id,name:'新礼盒',pict_id:icon.pict_id,item_type:'GACHA',function:'GACHA_EXEC',function_value:fn,love_up_price:0,max_owned:99999,daily_limited:0,description:'打开随机获得奖池中的一项奖励。'},profile:{item_id:id,function_value:fn,rewards:[],reward_pool:[],evidence:'LOCAL_POLICY_ADMIN_CUSTOM_BOX'},icon_source_id:icon.id});collectionEditor.boxID=id;collectionChanged();renderCollections();$('#box-name').focus();$('#box-name').select()};
for(const [id,key] of [['#box-name','name'],['#box-description','description'],['#box-maximum','max_owned']])$(id).oninput=()=>{const b=currentBox();if(!b)return;b.item[key]=key==='max_owned'?Number($(id).value):$(id).value;if(key==='name')$('#box-select option:checked').textContent=`${b.item.name} · ${b.item.item_id}`;collectionChanged()};
$('#box-icon').onchange=()=>{const b=currentBox(),icon=collectionEditor.icons.find(i=>i.id===Number($('#box-icon').value));if(b&&icon){b.icon_source_id=icon.id;b.item.pict_id=icon.pict_id;collectionChanged()}};
$('#box-add-rewards').onclick=()=>openContentPicker(rows=>{const b=currentBox();if(!b)return;if(b.profile.reward_pool.length+rows.length>100)throw new Error('每个礼盒最多100项奖励');for(const row of rows)b.profile.reward_pool.push({reward:contentReward(row),weight:1});collectionChanged();renderBoxPool()},['material','item','card','costume','honor']);
$('#box-add-honor').onclick=()=>{const b=currentBox(),h=collectionEditor.config.honors.find(h=>h.honor_id===Number($('#box-custom-honor').value));if(!b||!h)return;if(b.profile.reward_pool.length>=100){toast('每个礼盒最多100项奖励',true);return}b.profile.reward_pool.push({reward:{type:18,reward_typeid:h.honor_id,num:1,card_lv:0,card_fame:0,card_love:0,card_skill_lv:[]},weight:1});collectionChanged();renderBoxPool()};
async function collectionAction(fn){if(policyBusy('collections'))return;state.publishing.add('collections');updatePolicyControls();try{await fn()}catch(e){toast(e.message,true)}finally{state.publishing.delete('collections');updatePolicyControls()}}
$('#collection-save').onclick=()=>collectionAction(async()=>{const data=await api('/api/collections',{method:'PUT',body:JSON.stringify({expected_revision:collectionEditor.revision,config:collectionEditor.config})});collectionEditor.config=data.config;collectionEditor.revision=data.revision;collectionEditor.dirty=false;renderCollections();$('#collection-status').textContent='配置已保存。生成更新包，覆盖资源并重启后生效。';toast('配置已保存')});
$('#collection-package').onclick=()=>collectionAction(async()=>{if(collectionEditor.dirty)throw new Error('请先保存当前修改，再生成更新包');const response=await fetch('/api/collections/export',{method:'POST',headers:{'Content-Type':'application/json','X-Kairisei-Admin-Action':'apply'},body:JSON.stringify({expected_revision:collectionEditor.revision})});if(!response.ok){const data=await response.json();throw new Error(data.error||'生成失败')}const blob=await response.blob(),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=`称号与礼盒资源-v${collectionEditor.revision}.zip`;a.click();setTimeout(()=>URL.revokeObjectURL(url),60000);$('#collection-status').textContent=`已生成 v${collectionEditor.revision} 更新包。停服备份后按包内说明覆盖资源并重启，再让客户端下载更新资源。`;toast('资源更新包已生成')});
$('#collection-json').onclick=()=>downloadContent(collectionEditor.config,'称号与礼盒配置.json');
$('#collection-import').onchange=()=>collectionAction(async()=>{const next=await importContent($('#collection-import'));if(!next)return;if(!Array.isArray(next.honors)||!Array.isArray(next.boxes))throw new Error('配置须包含 honors 和 boxes 数组');if(!confirm('导入将替换当前草稿，继续？'))return;for(const b of next.boxes){if(!b.item||!b.profile||!Array.isArray(b.profile.reward_pool))throw new Error('礼盒配置格式不正确')}collectionEditor.config=next;collectionEditor.honorID=next.honors[0]?.honor_id||0;collectionEditor.boxID=next.boxes[0]?.item.item_id||0;collectionEditor.nextHonor=Math.max(collectionEditor.nextHonor,...next.honors.map(h=>h.honor_id+1));collectionEditor.nextBox=Math.max(collectionEditor.nextBox,...next.boxes.map(b=>b.item.item_id+1));collectionEditor.nextFunction=Math.max(collectionEditor.nextFunction,...next.boxes.map(b=>b.item.function_value+1));collectionChanged();renderCollections()});
